# fly.toml app configuration file generated for gosocial on 2024-12-03T17:34:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gosocial'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.23.3'

[env]
  PORT = '8080'
  SERVER_ORIGIN = 'https://gosocial.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
